 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 808-114-961
127.0.0.1 - - [21/Mar/2025 09:45:56] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:46:00] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:46:56] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:47:26] "[33mGET /favicon.ico HTTP/1.0[0m" 404 -
127.0.0.1 - - [21/Mar/2025 09:52:32] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:53:24] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:54:44] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:55:28] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:55:38] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:55:41] "[33mGET /favicon.ico HTTP/1.0[0m" 404 -
127.0.0.1 - - [21/Mar/2025 09:55:43] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:55:59] "GET / HTTP/1.0" 200 -
127.0.0.1 - - [21/Mar/2025 09:56:14] "[33mGET /favicon.ico HTTP/1.0[0m" 404 -
127.0.0.1 - - [21/Mar/2025 09:59:27] "GET / HTTP/1.0" 200 -
 * Detected change in '/home/vishwanathacharyadevopsone/app.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/home/vishwanathacharyadevopsone/app.py", line 2, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
